version: "3"
services:
  personal-space-client:
    build:
      context: ./frontend
    image: personal-space-client
    stdin_open: true
    ports:
      - "3000:80"
    networks:
      - mern-app
  personal-space-server:
    build:
      context: ./backend
    image: personal-space-server
    ports:
      - "5000:5000"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local